### PR TITLE
Updating export/import images.

### PR DESCRIPTION
**Pull request by skylerseverns**

### CODE REVIEW

**Comment by croffler** [comment]
where do you use these new pictures ?

**Comment by skylerseverns** [comment]
These new pictures are used in the sbp/export-import page. I copied the same pattern as before, delete the old image that was once used, now replaced by two images (one for import, one for export)

**Comment by croffler** [comment]
pls put them in the xap-docs-sbp repository not in the xap-doc repository

On Dec 17, 2015, at 7:22 PM, Skyler Severns wrote:

These new pictures are used in the sbp/export-import page. I copied the same pattern as before, delete the old image that was once used, now replaced by two images (one for import, one for export)

**Comment by skylerseverns** [comment]
Ok I've moved them to sbp, but this pull still needs to take place. It will remove an unused file.

**Pull request merged**
