### PR TITLE
Update running-gigaspaces-as-a-windows-service.markdown

### PR DESCRIPTION
**Pull request by yuvaldori**
wrapper.jar must be in the service classpath

### CODE REVIEW

**Comment by croffler** [comment]
Can you tell me which version works ?

**Comment by yuvaldori** [comment]
Hi Chris,
This is what I have added:

For downloading wrapper.jar go to [Java Service Wrapper](http://wrapper.tanukisoftware.org/), download wrapper-windows-xxx-xx-x.x.xx-pro.zip which fits to your platform, unzip it and copy wrapper-windows-xxx-xx-x.x.xx-pro\lib\wrapper.jar to your myApp\lib dir (or to any dir on your file system and point to it in your classpath)

What version are you talking about?

Regards,

Yuval

**Comment by croffler** [comment]
Sorry, the version of the wrapper

I can make a "macro" so when  the version of the wrapper changes we do not have to change the docs  just bump the version of the wrapper in the config.toml file.

Thanks
Chris

On Jan 6, 2016, at 11:06 AM, yuvaldori wrote:

Hi Chris,
This is what I have added:

For downloading wrapper.jar go to [Java Service Wrapper](http://wrapper.tanukisoftware.org/), download wrapper-windows-xxx-xx-x.x.xx-pro.zip which fits to your platform, unzip it and copy wrapper-windows-xxx-xx-x.x.xx-pro\lib\wrapper.jar to your myApp\lib dir (or to any dir on your file system and point to it in your classpath)

What version are you talking about?

Regards,

Yuval

**Comment by yuvaldori** [comment]
It has no version.
There is version for “wrapper-windows-x86-32-3.5.27-pro” when download it from this site: http://wrapper.tanukisoftware.com/doc/english/download.jsp but the user should choose it.

**Comment by croffler** [comment]
OK

so what you are saying; any version of the wrapper should work with any version of XAP ?

On Jan 6, 2016, at 11:36 AM, yuvaldori wrote:

It has no version.
There is version for “wrapper-windows-x86-32-3.5.27-pro” when download it from this site: http://wrapper.tanukisoftware.com/doc/english/download.jsp but the user should choose it.

**Comment by yuvaldori** [comment]
What I have toled you is not 100 present true.
When checking the wrapper.jar manifest, this is what I see:

Manifest-Version: 1.0
Ant-Version: Apache Ant 1.7.1
Created-By: 1.4.2_17-b06 (Sun Microsystems Inc.)
Built-By: leif
Package: org.tanukisoftware.wrapper
Extension-Name: wrapper
Specification-Title: Java Service Wrapper
Specification-Vendor: Tanuki Software, Ltd.
Specification-Version: 3.5.27
Implementation-Title: org.tanukisoftware.wrapper
Implementation-Vendor: Tanuki Software, Ltd.
Implementation-Version: 3.5.27

But the jar name doesn’t contain version.

Regarding XAP version, I’m not sure but I guess it depends on both java version.
Not sure that XAP compiling with java 6 with will work with wrapper.jar compiled with java 8

**Comment by croffler** [comment]
Hmmm .... the downloadable version of XAP is compiled with which version of Java ?

Not sure how to handle this .....

On Jan 6, 2016, at 12:02 PM, yuvaldori wrote:

What I have toled you is not 100 present true.
When checking the wrapper.jar manifest, this is what I see:

Manifest-Version: 1.0
Ant-Version: Apache Ant 1.7.1
Created-By: 1.4.2_17-b06 (Sun Microsystems Inc.)
Built-By: leif
Package: org.tanukisoftware.wrapper
Extension-Name: wrapper
Specification-Title: Java Service Wrapper
Specification-Vendor: Tanuki Software, Ltd.
Specification-Version: 3.5.27
Implementation-Title: org.tanukisoftware.wrapper
Implementation-Vendor: Tanuki Software, Ltd.
Implementation-Version: 3.5.27

But the jar name doesn’t contain version.

Regarding XAP version, I’m not sure but I guess it depends on both java version.
Not sure that XAP compiling with java 6 with will work with wrapper.jar compiled with java 8

**Comment by yuvaldori** [comment]
Don’t think that we should deep inside it. They should go to http://wrapper.tanukisoftware.com/doc/english/download.jsp
Choose the one that fits to their OS and copy it to their  myApp.zip. That’s it.

**Comment by croffler** [comment]
Ok

On Jan 10, 2016, at 5:56 PM, yuvaldori wrote:

Don’t think that we should deep inside it. They should go to http://wrapper.tanukisoftware.com/doc/english/download.jsp
Choose the one that fits to their OS and copy it to their myApp.zip. That’s it.

**Pull request merged**
